python train.py \
  --data_root data/coco2017 \
  --image_size 384 \
  --batch_size 64 \
  --val_batch_size 128 \
  --epochs 50 \
  --warmup_epochs 2 \
  --lr 5e-4 \
  --drop_path 0.1 \
  --amp \
  --accum_steps 1 \
  --out_dir runs/linformer_b16_coco384